apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::022633227919:role/eksctl-simple-jwt-api-nodegroup-NodeInstanceRole-19IPHFPA4FXOO
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::022633227919:role/UdacityFlaskDeployCBKubectlRole
      username: build         
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-13T11:34:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "846"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: bb842a5b-5a8a-4fa5-9ffa-d584db7f5d57
