apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::022633227919:role/jwt-stck-myjwt-CodeBuildServiceRole-1UPBODHHVVUGO
      username: system:node:{{EC2PrivateDNSName}}
      rolearn: arn:aws:iam::022633227919:role/UdacityFlaskDeployCBKubectlRole99
       username: build
       groups:
         - system:masters
  mapUsers: |
   - userarn: arn:aws:iam::022633227919:user/monadadmin
       username: monadadmin
       groups:
           - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-04T23:34:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "982"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b30f93e0-793f-4e19-a0f1-e619c6e67f4a
